language: python

python:
  - "3.7.4"

install:
  - pip3 install asyncio websockets numpy progressbar matplotlib

script: 
  - python -m  doctest -v  lab1/lab1_task2.py
  - python -m doctest -v lab2/task_one.py
  - python -m doctest -v lab2/task_two.py
  - python -m doctest -v lab3/tests.py
